// import { AppShellOptions } from 'modules/app-shell/src/lib/app-shell/shell-options';
import { OrganisationsPageComponent } from './organisations-page/organisations-page.component';
import { AppShellOptions } from '@ngx-fire-ui/app-shell';

const organisasjoner = {
  route: 'organisations',
  label: 'Organisasjoner',
  icon: 'account_balance',
};
const ansatte = {
  route: 'employees',
  label: 'Ansatte',
  icon: 'people',
};

export const shellOptions: AppShellOptions = {
  menuItems: [
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
    organisasjoner,
    ansatte,
  ],
  iconUrl: 'Hello from example-app custom icon url.',
};
